version: '3.8'
services:
  github-runner:
    image: michaelakridge326/github-actions-sh-runner:v1.0.0
    container_name: my-github-runner
    environment:
      - GH_REPO_URL=https://github.com/your_name/your_repo_here 
      - GH_RUNNER_NAME=my-docker-gh-runner-name-02
    secrets:
      - gh_pat
    volumes:
      - runner_work:/actions-runner/_work
    restart: unless-stopped
    networks:
      - runner-network
volumes:
  runner_work:
secrets:
  gh_pat:
    file: ./secrets/gh_pat.txt
networks:
  runner-network:
    driver: bridge
