# docker-compose.yml
services:
  github-runner:
    image: michaelakridge326/github-actions-sh-runner
    container_name: my-github-runner
    environment:
      - GH_RUNNER_URL=https://github.com/your_name/your_repo_here
      - GH_RUNNER_TOKEN=your_gh_runner_token_here
      - GH_RUNNER_NAME=my-docker-gh-runner-name
    volumes:
      - runner_work:/actions-runner/_work
volumes:
  runner_work:
